config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      get :register
      get :login
      post :user_login
      post :user_register
      get  :logout
    end
  end
  resources :cars
  resources :drivers
  resources :dashboard ,only: [:index]
  resources :agreements
  resources :expenses
  resources :reports 

  resources :profiles

  get "profile" , to: "profiles#onwer" ,as: :onwer_profile

  root "users#login"


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        collection do
          post :user_login
          post :user_register
          get  :logout
        end
      end
      resources :cars
      resources :expenses
      resources :agreements
      resources :drivers
      resources :dashboard ,only: [:index] do 
        collection do
          get :earning
          get :expense
          get :profit
          get :unpaid_agreement
          get :agreement_this_month
        end
      end
      resources :reports
    end
  end


end

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container-fluid">
        <!-- <nav class="pull-left">
            <ul>
                <li>
                    <a href="">
                        Help Center
                    </a>
                </li>
            </ul>
        </nav> -->
        <div class="copyright pull-right">
            ExpressGo v1.0 | &copy; made by <a href="https://www.facebook.com/saqib2231">SixMens!</a>
        </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<div class="sidebar" data-active-color="danger">

    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="<%= root_url %>" class="simple-text">
                <img src="/assets/logo.png" class="img-fluid float-left" style="background: no-repeat;background: no-repeat;border: none;    height: 65px;">
            </a>
            <span></span>
        </div>

        <ul class="nav">
            <li class="<%= is_active == "dashboard" ? "active" : " " %>">
                <a href="<%= dashboard_index_url %>">
                    <i class="ti-panel"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="<%= is_active == "expenses" ? "active" : " " %>">
                <a href="<%= expenses_url %>">
                    <i class="ti-money"></i>
                    <p>Expenses</p>
                </a>
            </li>
            <li class="<%= is_active == "agreements" ? "active" : " " %>">
                <a href="<%= agreements_url %>">
                    <i class="ti-file"></i>
                    <p>Agreements</p>
                </a>
            </li>
            <% if  current_user and current_user.has_role? :owner%>
            <li class="<%= is_active == "reports" ? "active" : " " %>">
                <a href="<%= reports_url %>">
                    <i class="ti-pie-chart"></i>
                    <p>Reports</p>
                </a>
            </li>
            
            <li class="<%= is_active == "drivers" ? "active" : " " %>">
                <a href="<%= drivers_url %>">
                    <i class="ti-user"></i>
                    <p>Driver</p>
                </a>
            </li>
            <% end %>
            
        </ul>
    </div>
</div>

app/views/shared/_sidebar.html.erb
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Dashboard</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                 <li>
                   <a href="<%= new_expense_url %>"  class="btn btn-info btn-fill btn-wd">
                    <i class="ti-plus"></i> New Expenses</a>
                </li>
                <li>
                   <a href="<%= new_agreement_url %>"  class="btn btn-info btn-fill btn-wd">
                    <i class="ti-plus"></i> New Agreement            </a>
                </li>
                <li class="dropdown">
                    <a href="#administrator" class="dropdown-toggle btn-rotate" data-toggle="dropdown" aria-expanded="false">
                        <i class="ti-user"></i> <%=  current_user.roles.first.try(:name) == "owner" ? "Administrator" : "Driver"%> 
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<%= onwer_profile_url %>">Profile</a></li>
                        <li><a href="<%= logout_users_url %>" >Logout</a></li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
</nav>