config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      get :register
      get :login
      post :user_login
      post :user_register
      get  :logout
    end
  end
  resources :cars
  resources :drivers
  resources :dashboard ,only: [:index]
  resources :agreements
  resources :expenses
  resources :reports 

  resources :profiles

  get "profile" , to: "profiles#onwer" ,as: :onwer_profile

  root "users#login"


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        collection do
          post :user_login
          post :user_register
          get  :logout
        end
      end
      resources :cars
      resources :expenses
      resources :agreements
      resources :drivers
      resources :dashboard ,only: [:index] do 
        collection do
          get :earning
          get :expense
          get :profit
          get :unpaid_agreement
          get :agreement_this_month
        end
      end
      resources :reports
    end
  end


end

app/models/car.rb
class Car < ApplicationRecord

	has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }, default_url: "/assets/unknown.jpg"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	
	
	belongs_to :user

	has_many :agreements
	has_many :expenses

	def driver 
		user = User.find_by_car_id(self.id)
		return user
	end
end

app/controllers/api/v1/cars_controller.rb
class Api::V1::CarsController < ApplicationController
	skip_before_action :verify_authenticity_token
	def index
		@user = User.find_by_id(params[:user_id])
		@cars = @user.cars
	end

	def create 
		if params[:car] && params[:driver] && params[:user_id]
			@car = Car.new(param_car)
			@car.user_id = params[:user_id]

			if @car.save
				if save_driver(@car)

				else
					render :json=> {
						:error => "Car did not created. Please try again later."
					},:status => 400
				end
			else
				render :json=> {
					:error => "Car did not created. Please try again later."
				},:status => 400
			end

		else
			if params[:user_id].blank?
				render :json=> {
					:error => "User Not Login. Login First."
				},:status => 400
			else
				render :json=> {
					:error => "Car did not created. Please try again later."
				},:status => 400
			end
		end

	end 

	def update 
		@car = Car.find_by_id(params[:id])
		if @car.update(param_car)

		else
			render :json=> {
				:error => "Car did not update. Please try again later."
			},:status => 400

		end
	end

	def destroy 
		@car = Car.find_by_id(params[:id])
		if @car.blank?
			render :json=> {
				:error => "Car did not find. Please try again later."
			},:status => 400
		else

			if @car.destroy
				render :json=> {
					:success => "Car Destroy."
				},:status => 200
			else
				render :json=> {
					:error => "Car did not Destroy. Please try again later."
				},:status => 400
			end
		end

	end

	private

	def param_car
		params.require(:car).permit(:model,:color,:transmission,:fuel_type,:name,:user_id,:avatar)
	end

	def new_params
		params.require(:driver).permit(:first_name, :last_name, :address, :phone_number, :email, :password)
	end

	def process_avatar
		if params[:account] && params[:account][:avatar]
			data = StringIO.new(Base64.decode64(params[:account][:avatar][:data]))
			data.class.class_eval { attr_accessor :original_filename, :content_type }
			data.original_filename = params[:account][:avatar][:filename]
			data.content_type = params[:account][:avatar][:content_type]
			params[:account][:avatar] = data
		end
	end

	def save_driver(car)
		@already = User.find_by_email(params[:driver][:email])
		@user =  User.new(new_params)
		@user.car_id = car.id
		@user.driver_id = params[:user_id]
		
		if @already.blank?
			if @user.save
				@user.add_role :driver
				is_save = true
			else
				is_save = false
			end
		else 
			is_save = false
		end
		return is_save
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
	before_action :check_user 

	def index
		@cars = current_user.cars
	end 

	def new
		@car = Car.new
	end 

	def show
		session[:car_id] = params[:id]
		redirect_to dashboard_index_url 
	end

	def create 
		
		if !params[:car][:avatar].blank?
			uploaded_io = params[:car][:avatar]
			@file_path = Rails.root.join('public', 'uploads', uploaded_io.original_filename)
			if File.exist?(@file_path)
				generate_token()
			else

			end
			File.open(@file_path, 'wb') do |file|
				f = file.write(uploaded_io.read)
			end

			session[:car] = params[:car]
			session[:car]["avatar"] = @file_path

			if session[:car]
				redirect_to new_driver_url
			else 
				@car = Car.new
				render :new
			end 
		else
		    @car = Car.new
			render :new
		end
	end 

	def edit 
		@car = Car.find_by_id(params[:id])
	end 

	def update
		@car = Car.find_by_id(params[:id])
		if @car.update(param_car) 
			flash[:success] = 'Car Successfully Update!' 
			redirect_to cars_url
		else
			flash[:error] = 'Car Not Update Try Agian'  
			render :edit
		end 
	end

	def destroy 
		@car = Car.find_by_id(params[:id])
		if @car.destroy
			flash[:success] = 'Car Successfully Destroy!' 
			redirect_to cars_url
		else
			flash[:error] = 'Car Not Destroy Try Agian'  
			redirect_to cars_url
		end 
	end

	private

	def param_car
		params.require(:car).permit(:model,:color,:transmission,:fuel_type,:name,:user_id,:avatar)
	end

	def check_user
		if  current_user and current_user.has_role? :owner
			
		elsif current_user and current_user.has_role? :driver
			redirect_to  dashboard_index_url
		else
			redirect_to root_url
		end
	end

	
	def generate_token
		loop do
			@file_path = SecureRandom.base64(15).tr('+/=', '0aZ').strip.delete("\n")
			@file_path = Rails.root.join('public', 'uploads', @file_path)
			break @file_path unless File.exist?(@file_path)
		end
	end



end

app/helpers/api/v1/cars_helper.rb
module Api::V1::CarsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/edit.html.erb
    <div class="main-panel" style="width: 100%">

      <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="<%= cars_url %>">Dashboard
                </a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= new_car_url %>"  class="btn btn-info btn-fill btn-wd">
                            <i class="ti-plus"></i> Add Vehicle     
                        </a>
                    </li>

                    <li class="dropdown">
                        <a href="#administrator" class="dropdown-toggle btn-rotate" data-toggle="dropdown" aria-expanded="false">
                            <i class="ti-user"></i>  Administrator
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= onwer_profile_url %>">Profile</a></li>
                            <% if current_user.blank? %>
                            <li><a href="<%= login_users_url %>">Login</a></li>
                            <li><a href="<%= register_users_url %>">Register</a></li>
                            <% else %>
                            <li><a href="<%= logout_users_url %>">Logout</a></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Add Vehicle</h4>
                        </div>
                        <div class="content">
                            <%= form_for @car, url: car_url , html: { multipart: true }  do |f|%>
                           <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Car Name</label>
                                        <%= f.text_field :name ,:class=>"form-control border-input" ,:required => true %>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Model</label>
                                        <%= f.text_field :model ,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Color</label>
                                        <%= f.text_field :color ,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Transmission</label>
                                        <select name="car[transmission]" class="form-control border-input">
                                            <option>Automotic</option>
                                            <option>Manual</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Fuel type</label>
                                        <select name="car[fuel_type]" class="form-control border-input">
                                            <option>Gasoline</option>
                                            <option>Diesel</option>
                                            <option>Gas</option>
                                            <option>Electirc</option>
                                            <option>Hybrid</option>
                                        </select>
                                    </div>
                                </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Avatar</label>
                                        <%= f.file_field :avatar ,:required => true,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" name="confirm" class="btn btn-info btn-fill btn-wd">SAve
                                </button>
                            </div>
                            <div class="clearfix"></div>
                            <% end %>        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
       <%= render "shared/footer"%>

</div>

app/views/cars/index.html.erb
    <div class="main-panel" style="width: 100%">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="<%= cars_url %>">Dashboard</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= new_car_url %>"  class="btn btn-info btn-fill btn-wd">
                            <i class="ti-plus"></i> Add Vehicle     
                        </a>
                    </li>

                    <li class="dropdown">
                        <a href="#administrator" class="dropdown-toggle btn-rotate" data-toggle="dropdown" aria-expanded="false">
                            <i class="ti-user"></i>  Administrator
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= onwer_profile_url %>">Profile</a></li>
                            <% if current_user.blank? %>
                            <li><a href="<%= login_users_url %>">Login</a></li>
                            <li><a href="<%= register_users_url %>">Register</a></li>
                            <% else %>
                            <li><a href="<%= logout_users_url %>">Logout</a></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                 <% @cars.each do |car|%>
                 <div class="col-lg-3 col-sm-6">
                    <div class="card">
                        <div class="cover clearfix">
                            <img class="card-img-top" src="<%= car.avatar %>" alt="card image" style=
                            "height: 180px;width: 100%;display: block;">
                        </div>
                        <div class="card-body "  style="padding-bottom: 20px;">
                            <div class="row text-center">

                                <h4 class="card-title"><%= car.name %></h4>

                            </div>
                            <div class="row text-center">
                                <div class="col-sm-6">
                                    <p class="card-text"><%= car.model %></p>
                                </div>
                                <div class="col-sm-6">
                                    <p class="card-text"><%= car.color %></p>
                                </div>
                            </div>
                            <div class="row text-center">
                                <div class="col-sm-6">
                                    <p class="card-text"><%= car.transmission %></p>
                                </div>
                                <div class="col-sm-6">
                                    <p class="card-text"><%= car.fuel_type %></p>
                                </div>
                            </div>
                            <div class="row text-center">
                                <a href="<%= car_url(car)%>">
                                    <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-eye"></i></btn>
                                </a>
                                <a href="<%= edit_car_url(car) %>">
                                    <btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-edit"></i></btn>
                                </a>
                                <%= link_to car_url(car),  method: :delete, data: { confirm: 'Are you sure?' } ,:class=> "btn btn-sm btn-danger btn-icon" do %>
                                <i class="fa fa-remove"></i>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
       <%= render "shared/footer"%>

</div>
<style type="text/css">
.card {
    border: 4px solid #777777;
    border-radius: 10px; 
}
.clearfix{
   border-radius: 5px; 
   overflow: hidden;
}    
p{
   overflow-wrap: break-word;
}
</style>

app/views/cars/new.html.erb
    <div class="main-panel" style="width: 100%">

      <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="<%= cars_url %>">Dashboard
                </a>
                <div class="logo">
                    <a href="<%= root_url %>" class="simple-text">
                        <!-- ExpressGo -->
                        <img src="/assets/logo.png" class="img-fluid float-left" style="background: no-repeat;background: no-repeat;border: none;    height: 65px;">
                    </a>
                    <span></span>
                </div>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= new_car_url %>"  class="btn btn-info btn-fill btn-wd">
                            <i class="ti-plus"></i> Add Vehicle     
                        </a>
                    </li>

                    <li class="dropdown">
                        <a href="#administrator" class="dropdown-toggle btn-rotate" data-toggle="dropdown" aria-expanded="false">
                            <i class="ti-user"></i>  Administrator
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= onwer_profile_url %>">Profile</a></li>
                            <% if current_user.blank? %>
                            <li><a href="<%= login_users_url %>">Login</a></li>
                            <li><a href="<%= register_users_url %>">Register</a></li>
                            <% else %>
                            <li><a href="<%= logout_users_url %>">Logout</a></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Add Vehicle</h4>
                        </div>
                        <div class="content">
                            <%= form_for @car, url: cars_url , html: { multipart: true } do |f|%>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Car Name</label>
                                        <%= f.text_field :name ,:class=>"form-control border-input" ,:required => true %>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Model</label>
                                        <%= f.text_field :model ,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Color</label>
                                        <%= f.text_field :color ,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Transmission</label>
                                        <select name="car[transmission]" class="form-control border-input">
                                            <option>Automotic</option>
                                            <option>Manual</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Fuel type</label>
                                        <select name="car[fuel_type]" class="form-control border-input">
                                            <option>Gasoline</option>
                                            <option>Diesel</option>
                                            <option>Gas</option>
                                            <option>Electirc</option>
                                            <option>Hybrid</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Avatar</label>
                                        <%= f.file_field :avatar ,:required => true,:class=>"form-control border-input"%>
                                    </div>
                                </div>
                            </div>
                            <div class="text-center">
                                <button type="submit" name="confirm" class="btn btn-fill btn-wd">Next
                                </button>
                            </div>
                            <div class="clearfix"></div>
                            <% end %>        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
       <%= render "shared/footer"%>

</div>
<style type="text/css">
.card {
    border: 4px solid #777777;
    border-radius: 10px; 
}
.clearfix{
    border-radius: 5px; 
    overflow: hidden;
}    
p{
    overflow-wrap: break-word;
}
</style>