config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    collection do
      get :register
      get :login
      post :user_login
      post :user_register
      get  :logout
    end
  end
  resources :cars
  resources :drivers
  resources :dashboard ,only: [:index]
  resources :agreements
  resources :expenses
  resources :reports 

  resources :profiles

  get "profile" , to: "profiles#onwer" ,as: :onwer_profile

  root "users#login"


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        collection do
          post :user_login
          post :user_register
          get  :logout
        end
      end
      resources :cars
      resources :expenses
      resources :agreements
      resources :drivers
      resources :dashboard ,only: [:index] do 
        collection do
          get :earning
          get :expense
          get :profit
          get :unpaid_agreement
          get :agreement_this_month
        end
      end
      resources :reports
    end
  end


end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < ApplicationController

	skip_before_action :verify_authenticity_token
	before_action :get_car
	
	def index 
		if @car.blank?
			render :json=> {
				:error => "No Car find."
			},:status => 400
		else

			if !params[:report].blank?
				@from = params[:report][:date_from].to_time.beginning_of_day
				@to = params[:report][:date_to].to_time.end_of_day
			else
				@from = Time.now.beginning_of_month
				@to = Time.now.end_of_month
			end
			@agreements = @car.agreements.where("start_date >= ? AND end_date <= ?", @from , @to).paginate(page: params[:page])
			@expenses = @car.expenses.where(datetime: @from..@to)
			@total = @agreements + @expenses
			@total = @total.paginate(:page => params[:page], :per_page => 10)
			@sort_array = @total.sort_by{|e| e.class.name == "Expense" ? e[:datetime] : e[:start_date] }
		end
	end 

	private 

	def get_car
		@car = Car.find_by_id(params[:car_id])
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	
	before_action :check_user 
	before_action :get_car
	
	def index 
		if !params[:report].blank?
			@from = params[:report][:date_from].to_time.beginning_of_day
			@to = params[:report][:date_to].to_time.end_of_day
		else
			@from = Time.now.beginning_of_month
			@to = Time.now.end_of_month
		end
		@agreements = @car.agreements.where("start_date >= ? AND end_date <= ?", @from , @to).paginate(page: params[:page])
		@expenses = @car.expenses.where(datetime: @from..@to)
		@total = @agreements + @expenses
		@total = @total.paginate(:page => params[:page], :per_page => 10)
		@sort_array = @total.sort_by{|e| e.class.name == "Expense" ? e[:datetime] : e[:start_date] }
	end 

	private 

	def get_car
		@car = Car.find_by_id(session[:car_id])
	end
	def check_user
		if current_user and current_user.roles.first.try(:name) == "owner"
			
		elsif 
			redirect_to dashboard_index_url
		else
			redirect_to root_url
		end
	end

end

app/helpers/api/v1/reports_helper.rb
module Api::V1::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper

	def total_expense(car, from, to)
		expenses = car.expenses.where(datetime: from.to_time.beginning_of_day..to.to_time.end_of_day)
		cost = []
		expenses.each do |exp|
			cost.push(exp.price)
		end 
		cost = cost.reject(&:blank?)
		return cost.inject(&:+)
	end

	def total_agreement(car, from, to)
	    agreements = car.agreements.where("start_date >= ? AND end_date <= ?", from.to_time.beginning_of_day , to.to_time.end_of_day)
		earn = []
		agreements.each do |agr|
			if agr.is_paid == "paid"
				earn.push(agr.price)
			else 

			end
		end 
		earn = earn.reject(&:blank?)
		return earn.inject(&:+)
	end
	def total_profit(car, from, to)
		total_earn = total_agreement(car, from, to)
		total_cost = total_expense(car, from, to)
		earn = !total_earn.blank? ? total_earn : 0
		cost = !total_cost.blank? ? total_cost : 0
		profit = earn - cost 
		return profit
	end

end

app/views/reports/_index.html.erb
<style type="text/css">
.bg-danger {
	background-color: #fcb7622b !important;
}
</style>

<div class="content table-responsive table-full-width">
	<div class="bootstrap-table">
		<div class="fixed-table-toolbar">
			<div class="pull-left search">
				<!-- <input class="form-control" type="text" placeholder="Search"> -->
			</div>
		</div>
		<div class="fixed-table-container" style="padding-bottom: 0px;">
			<div class="fixed-table-body">
				<table class="table table-striped table-hover text-center">
					<thead>
						<tr>
							<th class="text-center">
								<div class="th-inner ">
									First name/Last name
								</div>
								<div class="fht-cell"></div>
							</th>
							<th class="text-center">
								<div class="th-inner ">
									Cell phone
								</div>
								<div class="fht-cell"></div>
							</th>
							<th class="text-center">
								<div class="th-inner ">
									Start date/End date
								</div>
								<div class="fht-cell">

								</div>
							</th>
							<th class="text-center">
								<div class="th-inner ">
									Amount
								</div>
								<div class="fht-cell"></div>
							</th>
							<th class="text-center">
								<div class="th-inner ">
									Paid / Unpaid
								</div>
								<div class="fht-cell"></div>
							</th>
							<th class="text-center">
								<div class="th-inner ">
									Operation
								</div>
								<div class="fht-cell"></div>
							</th>
						</tr>
					</thead>
					<tbody>
						<% @sort_array.each do |agr|%>
						<%if agr.class.name == "Agreement"%>
						<tr>
							<td><%= agr.fullname %></td>
							<td><%= agr.phone_number %></td>
							<td><%= agr.start_date.to_s.split('UTC')[0] %> / <%= agr.end_date.to_s.split('UTC')[0] %> </td>
							<td><%= agr.price %> </td>
							<% if agr.is_paid == "unpaid" %>
							<td><label class="label label-danger white">Unpaid</label></td>
							<% elsif agr.is_paid == "paid"%>
							<td><label class="label label-success white">Paid</label></td>
							<% else%>
							<td><label class="label label-primary white">Void</label></td>
							<% end %>
							<td>
								<a href="<%= edit_agreement_url(agr) %>">

									<btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-edit"></i></btn>
								</a>
								<a href="<%= agreement_url(agr) %>">

									<btn class="btn btn-sm btn-info btn-icon"><i class="fa fa-eye"></i></btn>
								</a>
							</td>
						</tr>
						<% else%>
						<tr class="bg-danger">
							<td><%= agr.name %></td>
							<td></td>
							<td><%= agr.datetime.to_s.split('UTC')[0] %></td>
							<td><%= agr.price %></td>
							<td></td>

							<td>
								<a href="<%= expense_url(agr)%>">
									<btn class="btn btn-sm btn-success btn-icon"><i class="fa fa-eye"></i></btn>
								</a>
								<%= link_to   expense_url(agr),  method: :delete, data: { confirm: 'Are you sure?' } ,:class=> "btn btn-sm btn-danger btn-icon" do %>
								<i class="fa fa-remove"></i>
								<% end %>
							</td>
						</tr>
						<% end %>
						<% end %>
						<tr>
							<td colspan="5">
								Total Earning
							</td >
							<td><%= total_agreement(@car, @from, @to)%></td>
							
						</tr>

						<tr>
							<td colspan="5">
								Total Expenses
							</td >
							<td><%= total_expense(@car, @from, @to)%></td>
						</tr>
						<tr>
							<td colspan="5">
								Profit
							</td >
							<td><%= total_profit(@car, @from, @to)%></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="fixed-table-pagination">
				<div class="pull-right pagination">
					<%= will_paginate @total ,renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/reports/index.html.erb
<%= render "shared/header"%>
<div class="main-panel">
	<%= render "shared/sidebar"%>
	<div class="content">
		<div class="container-fluid">

			<div class="row">
				<div class="col-lg-12">
					<div class="card">
						<div class="header">
							<h4 class="title">Reports</h4>
						</div>

						<div class="content">
							<%= form_for :report , url: reports_url ,:html => { :method => 'GET' }  do |f|%>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<div>
											<label>Start date</label>
											<input type="text" name="report[date_from]" value="" class="form-control border-input" id="start_time" placeholder="" readonly required>
										</div>
									</div>
								</div>

								<div class="col-md-6">
									<div class="form-group">
										<div>
											<label>End date</label>
											<input type="text" id="end_time" name="report[date_to]" value="" class="form-control border-input" readonly placeholder="" required>
										</div>
									</div>
								</div>

								<div class="text-center">
									<button type="submit" name="confirm" class="btn btn-info btn-fill btn-wd" >Get report</button>
								</div>

							</div>
							<% end %>
							<div class="row">
								<div class="col-md-12">
									<div class="content table-responsive table-full-width">
										<%= render "index" %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	 <%= render "shared/footer"%>
</div>


<script type="text/javascript">


	$('#start_time').datepicker({
		dateFormat: "yy-mm-dd",
		
		onClose: function(dateText, inst) {
			if ($("end_time").val() != '') {
				var testStartDate = $('#start_time').datepicker('getDate');
				var testEndDate = $("#end_time").datepicker('getDate');
				if (testStartDate > testEndDate)
					$("#end_time").datepicker('setDate', testStartDate);
			}
			else {
				$("#end_time").val(dateText);
			}
		},
		onSelect: function (selectedDateTime){
			$("#end_time").datepicker('option', 'minDate', $('#start_time').datepicker('getDate') );
		}
	});



	$('#end_time').datepicker({
		minDate: $("#start_time").val(),
		dateFormat: "yy-mm-dd",
		
		onClose: function(dateText, inst) {
			if ($('#start_time').val() != '') {
				var testStartDate = $('#start_time').datepicker('getDate');
				var testEndDate = $("#end_time").datepicker('getDate');
				if (testStartDate > testEndDate)
					$('#start_time').datepicker('setDate', testEndDate);
			}
			else {
				$('#start_time').val(dateText);
			}
		},
		onSelect: function (selectedDateTime){
			$('#start_time').datepicker('option', 'maxDate', $("#end_time").datepicker('getDate') );
		}
	});




</script>